DROP TABLE AUTH;

DROP TABLE MEMBER;



SELECT * FROM BOARD;

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('오늘 저녁에 하늘마당에서 보실 분','내가 치킨 쏜다', '명훈쌤');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('HOW MANY?','FAST FORWARD', '전소미');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('LEMON MINT', 'HALLS', 'KK');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('MENTHOLYPTUS','HALLS', 'J');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('UDON','FROM SANRIO', '한교동');

SELECT * FROM MEMBER;